CREATE TABLE "Clientes" (
  "ID_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Nome_cliente" "Varchar(100)" NOT NULL,
  "CPF" char(11) UNIQUE NOT NULL,
  "Telefone" varchar(20),
  "ID_professor" int
);

CREATE TABLE "Frequencia" (
  "ID_frequencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ID_cliente" int NOT NULL,
  "Entrada" datetime,
  "Saida" datetime
);

CREATE TABLE "Professores" (
  "ID_professor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Nome_professor" varchar(100) NOT NULL,
  "status_professor" varchar(20),
  "Especialidade" varchar(20)
);

CREATE TABLE "Pagamentos" (
  "ID_pagamento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ID_matricula" int NOT NULL,
  "Metodo_pagamento" varchar(15) NOT NULL,
  "Data_pagamento" date,
  "status" varchar(25) NOT NULL,
  "Valor_pago" decimal(10,2) NOT NULL
);

CREATE TABLE "Planos" (
  "ID_plano" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Nome_plano" varchar(25) NOT NULL,
  "Valor" decimal(10,2) NOT NULL,
  "descricao" varchar(10),
  "duracao" varchar(20)
);

CREATE TABLE "Matriculas" (
  "ID_matricula" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ID_cliente" int NOT NULL,
  "ID_plano" INT NOT NULL,
  "Data_inicio" date NOT NULL,
  "Data_fim" date NOT NULL,
  "status" varchar(10) NOT NULL
);

CREATE TABLE "Produtos" (
  "ID_produto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Nome_produto" varchar(25) NOT NULL,
  "Estoque" int,
  "preco" decimal(10,2) NOT NULL
);

CREATE TABLE "Consumos" (
  "ID_consumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ID_cliente" int NOT NULL,
  "Data_consumo" date NOT NULL,
  "Valor_total" decimal(10,2) NOT NULL
);

CREATE TABLE "Itens_consumo" (
  "ID_item" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ID_consumo" int NOT NULL,
  "ID_produto" int NOT NULL,
  "Quantidade" int,
  "preco" decimal(10,2) NOT NULL
);

ALTER TABLE "Professores" ADD FOREIGN KEY ("ID_professor") REFERENCES "Clientes" ("ID_professor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Clientes" ADD FOREIGN KEY ("ID_cliente") REFERENCES "Consumos" ("ID_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consumos" ADD FOREIGN KEY ("ID_consumo") REFERENCES "Itens_consumo" ("ID_consumo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Produtos" ADD FOREIGN KEY ("ID_produto") REFERENCES "Itens_consumo" ("ID_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Clientes" ADD FOREIGN KEY ("ID_cliente") REFERENCES "Matriculas" ("ID_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Planos" ADD FOREIGN KEY ("ID_plano") REFERENCES "Matriculas" ("ID_plano") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Matriculas" ADD FOREIGN KEY ("ID_matricula") REFERENCES "Pagamentos" ("ID_matricula") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Clientes" ADD FOREIGN KEY ("ID_cliente") REFERENCES "Frequencia" ("ID_cliente") DEFERRABLE INITIALLY IMMEDIATE;
